#server:
#  port: 8080
#
#app:
#  name: spring.dbs
#
#spring:
#  datasource:
#    url: jdbc:log4jdbc:mysql://localhost:3306/spring_dbs_01?connectionLifecycleInterceptors=spring.mysql.monitor.ConnectionLifecycleInterceptorImpl
#    username: root
#    password: 123456
#    driver-class-name: net.sf.log4jdbc.DriverSpy